source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "~> 3.1"

gem "rails", "~> 7.0.2", ">= 7.0.2.2"

gem "activerecord-session_store"
gem "bootsnap", require: false
gem "devise", "~> 4.8"
gem "dotenv-rails"
gem "hotwire-rails", "~> 0.1.3"
gem "image_processing", "~> 1.2"
gem "importmap-rails"
gem "jbuilder"
gem "jwt"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "redis", "~> 4.0"
gem 'rest-client'
gem "sprockets-rails"
gem "stimulus-rails"
gem "tailwindcss-rails"
gem "turbo-rails"
gem 'twitter_oauth2'
gem 'uri-query_params'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "pry"
  gem "pry-byebug"
end

group :development do
  gem "web-console"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
